<a href="https://colab.research.google.com/github/finterstellar/lecture/blob/master/%ED%8C%8C%EC%9D%B4%EC%8D%AC_%EA%B8%B0%EC%B4%88_03.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

[finance data reader](https://financedata.github.io/posts/finance-data-reader-users-guide.html)

In [ ]:
pip install finance-datareader

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Requirement already satisfied: finance-datareader in /usr/local/lib/python3.8/dist-packages (0.9.50)
Requirement already satisfied: pandas>=0.19.2 in /usr/local/lib/python3.8/dist-packages (from finance-datareader) (1.3.5)
Requirement already satisfied: requests>=2.3.0 in /usr/local/lib/python3.8/dist-packages (from finance-datareader) (2.25.1)
Requirement already satisfied: tqdm in /usr/local/lib/python3.8/dist-packages (from finance-datareader) (4.64.1)
Requirement already satisfied: requests-file in /usr/local/lib/python3.8/dist-packages (from finance-datareader) (1.5.1)
Requirement already satisfied: lxml in /usr/local/lib/python3.8/dist-packages (from finance-datareader) (4.9.2)
Requirement already satisfied: python-dateutil>=2.7.3 in /usr/local/lib/python3.8/dist-packages (from pandas>=0.19.2->finance-datareader) (2.8.2)
Requirement already satisfied: pytz>=2017.3 in /usr/local/lib/python3.8/dist-packages (from pandas>=0.19.2->finance-datareader) (2022.7)
Requirement already satisfied: numpy>=1.17.3 in /usr/local/lib/python3.8/dist-packages (from pandas>=0.19.2->finance-datareader) (1.21.6)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /usr/local/lib/python3.8/dist-packages (from requests>=2.3.0->finance-datareader) (1.24.3)
Requirement already satisfied: idna<3,>=2.5 in /usr/local/lib/python3.8/dist-packages (from requests>=2.3.0->finance-datareader) (2.10)
Requirement already satisfied: chardet<5,>=3.0.2 in /usr/local/lib/python3.8/dist-packages (from requests>=2.3.0->finance-datareader) (4.0.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.8/dist-packages (from requests>=2.3.0->finance-datareader) (2022.12.7)
Requirement already satisfied: six in /usr/local/lib/python3.8/dist-packages (from requests-file->finance-datareader) (1.15.0)

In [ ]:
import FinanceDataReader as fdr

In [ ]:
df_krx = fdr.StockListing('KRX')
df_krx

,Code,ISU_CD,Name,Market,Dept,Close,ChangeCode,Changes,ChagesRatio,Open,High,Low,Volume,Amount,Marcap,Stocks,MarketId
0,005930,KR7005930003,삼성전자,KOSPI,,57800,1,2400,4.33,55700,58000,55600,20129924,1148115799800,345650409645000,5969782550,STK
1,373220,KR7373220003,LG에너지솔루션,KOSPI,,443000,1,2500,0.57,433000,445000,421000,289760,125467599500,103194000000000,234000000,STK
2,000660,KR7000660001,SK하이닉스,KOSPI,,81000,1,5400,7.14,75400,81900,75200,5137806,410099099100,59186592274500,728002365,STK
3,207940,KR7207940008,삼성바이오로직스,KOSPI,,794000,2,-9000,-1.12,800000,802000,783000,71925,56928723000,56583330000000,71174000,STK
4,005935,KR7005931001,삼성전자우,KOSPI,,52100,1,1600,3.17,50400,52400,50400,1252335,64452022600,42954685740000,822886700,STK
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2685,267810,KR7267810000,앙츠,KONEX,일반기업부,1010,3,0,0.00,1010,1150,1010,761,861010,2055050000,1787000,KNX
2686,215050,KR7215050006,비엔디생활건강,KONEX,일반기업부,912,0,0,0.00,0,0,0,0,0,1934959392,2121666,KNX
2687,288490,KR7288490006,나라소프트,KONEX,일반기업부,47,3,0,0.00,48,49,40,33067,1432278,1792909000,38147000,KNX
2688,267060,KR7267060002,명진홀딩스,KONEX,일반기업부,181,0,0,0.00,0,0,0,0,0,1654666524,9141804,KNX
2689,322190,KR7322190000,베른,KONEX,일반기업부,152,1,7,4.83,125,162,125,889,137839,1383405535,8925197,KNX

In [ ]:
df_spx = fdr.StockListing('S&P500')
df_spx.head()

  Symbol         Name                  Sector                        Industry
0    MMM           3M             Industrials        Industrial Conglomerates
1    AOS  A. O. Smith             Industrials               Building Products
2    ABT       Abbott             Health Care           Health Care Equipment
3   ABBV       AbbVie             Health Care                 Pharmaceuticals
4    ACN    Accenture  Information Technology  IT Consulting & Other Services

In [ ]:
df1 = fdr.DataReader('005930')
df1

             Open   High    Low  Close    Volume    Change
Date
1998-09-30    737    745    720    728    482440       NaN
1998-10-01    720    724    700    705    389970 -0.031593
1998-10-02    697    710    687    707    358110  0.002837
1998-10-07    720    736    708    709    783920  0.002829
1998-10-08    727    745    726    727    772740  0.025388
...           ...    ...    ...    ...       ...       ...
2022-12-28  57600  57600  56400  56600  14665410 -0.025818
2022-12-29  56000  56200  55300  55300  11295935 -0.022968
2023-01-02  55500  56100  55200  55500  10031448  0.003617
2023-01-03  55400  56000  54500  55400  13547030 -0.001802
2023-01-04  55700  58000  55600  57800  19997883  0.043321

[6000 rows x 6 columns]

In [ ]:
df2 = fdr.DataReader('AAPL')
df2

,Open,High,Low,Close,Adj Close,Volume
Date,,,,,,
1980-12-12,0.128348,0.128906,0.128348,0.128348,0.099874,469033600
1980-12-15,0.122210,0.122210,0.121652,0.121652,0.094663,175884800
1980-12-16,0.113281,0.113281,0.112723,0.112723,0.087715,105728000
1980-12-17,0.115513,0.116071,0.115513,0.115513,0.089886,86441600
1980-12-18,0.118862,0.119420,0.118862,0.118862,0.092492,73449600
...,...,...,...,...,...,...
2022-12-27,131.380005,131.410004,128.720001,130.029999,130.029999,69007800
2022-12-28,129.669998,131.029999,125.870003,126.040001,126.040001,85438400
2022-12-29,127.989998,130.479996,127.730003,129.610001,129.610001,75703700
2022-12-30,128.410004,129.949997,127.430000,129.929993,129.929993,76960600
2023-01-03,130.279999,130.899994,124.169998,125.070000,125.070000,111975500

In [ ]:
df1

             Open   High    Low  Close    Volume    Change
Date
1998-09-30    737    745    720    728    482440       NaN
1998-10-01    720    724    700    705    389970 -0.031593
1998-10-02    697    710    687    707    358110  0.002837
1998-10-07    720    736    708    709    783920  0.002829
1998-10-08    727    745    726    727    772740  0.025388
...           ...    ...    ...    ...       ...       ...
2022-12-28  57600  57600  56400  56600  14665410 -0.025818
2022-12-29  56000  56200  55300  55300  11295935 -0.022968
2023-01-02  55500  56100  55200  55500  10031448  0.003617
2023-01-03  55400  56000  54500  55400  13547030 -0.001802
2023-01-04  55700  58000  55600  57800  19997883  0.043321

[6000 rows x 6 columns]

dataframe concat 사용법 검색

In [ ]:
df = pd.concat([df1['Close'], df2['Close']], axis=1)
df

              Close       Close
Date
1980-12-12      NaN    0.128348
1980-12-15      NaN    0.121652
1980-12-16      NaN    0.112723
1980-12-17      NaN    0.115513
1980-12-18      NaN    0.118862
...             ...         ...
2022-12-29  55300.0  129.610001
2022-12-30      NaN  129.929993
2023-01-02  55500.0         NaN
2023-01-03  55400.0  125.070000
2023-01-04  57800.0         NaN

[10800 rows x 2 columns]

In [ ]:
df.columns = ['005930','AAPL']
df

             005930        AAPL
Date
1980-12-12      NaN    0.128348
1980-12-15      NaN    0.121652
1980-12-16      NaN    0.112723
1980-12-17      NaN    0.115513
1980-12-18      NaN    0.118862
...             ...         ...
2022-12-29  55300.0  129.610001
2022-12-30      NaN  129.929993
2023-01-02  55500.0         NaN
2023-01-03  55400.0  125.070000
2023-01-04  57800.0         NaN

[10800 rows x 2 columns]

In [ ]:
df.fillna(method='ffill', inplace=True)
df

             005930        AAPL
Date
1980-12-12      NaN    0.128348
1980-12-15      NaN    0.121652
1980-12-16      NaN    0.112723
1980-12-17      NaN    0.115513
1980-12-18      NaN    0.118862
...             ...         ...
2022-12-29  55300.0  129.610001
2022-12-30  55300.0  129.929993
2023-01-02  55500.0  129.929993
2023-01-03  55400.0  125.070000
2023-01-04  57800.0  125.070000

[10800 rows x 2 columns]

In [ ]:
df.dropna(axis=0, inplace=True)
df

             005930        AAPL
Date
1998-09-30    728.0    0.340402
1998-10-01    705.0    0.318638
1998-10-02    707.0    0.313058
1998-10-05    707.0    0.287388
1998-10-06    707.0    0.290737
...             ...         ...
2022-12-29  55300.0  129.610001
2022-12-30  55300.0  129.929993
2023-01-02  55500.0  129.929993
2023-01-03  55400.0  125.070000
2023-01-04  57800.0  125.070000

[6301 rows x 2 columns]

In [ ]:
df['rtn_005930'] = df['005930'].pct_change() * 100
df['rtn_AAPL'] = df['AAPL'].pct_change() * 100
df_sub = df.loc['2010-01-01':]
df_sub

             005930        AAPL  rtn_005930  rtn_AAPL
Date
2010-01-04  16180.0    7.643214    1.251564  1.556496
2010-01-05  16440.0    7.656429    1.606922  0.172898
2010-01-06  16820.0    7.534643    2.311436 -1.590637
2010-01-07  16260.0    7.520714   -3.329370 -0.184866
2010-01-08  16420.0    7.570714    0.984010  0.664830
...             ...         ...         ...       ...
2022-12-29  55300.0  129.610001   -2.296820  2.832434
2022-12-30  55300.0  129.929993    0.000000  0.246888
2023-01-02  55500.0  129.929993    0.361664  0.000000
2023-01-03  55400.0  125.070000   -0.180180 -3.740470
2023-01-04  57800.0  125.070000    4.332130  0.000000

[3374 rows x 4 columns]

[plotly official document](https://plotly.com/python/)

In [ ]:
import plotly.express as px

In [ ]:
fig = px.line(df_sub, y='AAPL')
fig.show()

In [ ]:
fig = px.area(df_sub, x=df_sub.index, y='AAPL')
fig.show()

In [ ]:
fig = px.area(df_sub, x=df_sub.index, y='AAPL', log_y=True)
fig.show()

In [ ]:
fig = px.area(df_sub, x=df_sub.index, y='rtn_AAPL')
fig.show()

In [ ]:
df_sub['rtn_AAPL'].std()

1.7835693321084354

1/4

김지윤, 이현우, 박무영, 박선우

삼성전자의 90일 이동평균선, 90일 변동성을 구하고 그래프로 그려보세요.

In [ ]:
fig = px.area(df_sub, x=df_sub.index, y='005930')
fig.show()

In [ ]:
df['MA_005930'] = df['005930'].rolling(90).mean()
df['MA_005930']

Date
1998-09-30             NaN
1998-10-01             NaN
1998-10-02             NaN
1998-10-05             NaN
1998-10-06             NaN
                  ...
2022-12-29    58130.000000
2022-12-30    58077.777778
2023-01-02    58043.333333
2023-01-03    58005.555556
2023-01-04    57984.444444
Name: MA_005930, Length: 6301, dtype: float64

In [ ]:
fig = px.line(df, x=df.index, y=['005930','MA_005930'])
fig.show()

In [ ]:
df['STD_005930'] = df['rtn_005930'].rolling(90).std()
df['STD_005930']

Date
1998-09-30         NaN
1998-10-01         NaN
1998-10-02         NaN
1998-10-05         NaN
1998-10-06         NaN
                ...
2022-12-29    1.641091
2022-12-30    1.639970
2023-01-02    1.622829
2023-01-03    1.622357
2023-01-04    1.678975
Name: STD_005930, Length: 6301, dtype: float64

In [ ]:
fig = px.line(df, x=df.index, y=['005930','STD_005930'])
fig.show()

In [ ]:
fig = px.area(df_sub, x=df_sub.index, y='005930', log_y=True)
fig.show()

[plotly doc](https://plotly.com/python/multiple-axes/)

In [ ]:
import plotly.graph_objects as go
from plotly.subplots import make_subplots

# Create figure with secondary y-axis
fig = make_subplots(specs=[[{"secondary_y": True}]])

# Add traces
fig.add_trace(
    go.Scatter(x=[1, 2, 3], y=[40, 50, 60], name="yaxis data"),
    secondary_y=False,
)

fig.add_trace(
    go.Scatter(x=[2, 3, 4], y=[4, 5, 6], name="yaxis2 data"),
    secondary_y=True,
)

# Set y-axes titles
fig.update_yaxes(title_text="<b>primary</b> yaxis title", secondary_y=False)
fig.update_yaxes(title_text="<b>secondary</b> yaxis title", secondary_y=True)

fig.show()

In [ ]:
import plotly.graph_objects as go
from plotly.subplots import make_subplots

# Create figure with secondary y-axis
fig = make_subplots(specs=[[{"secondary_y": True}]])

# Add traces
fig.add_trace(
    go.Scatter(x=df.index, y=df['005930'], name='005930'),
    secondary_y=False,
)

fig.add_trace(
    go.Scatter(x=df.index, y=df['STD_005930'], name='Volatility'),
    secondary_y=True,
)

# Set y-axes titles
fig.update_yaxes(title_text="Price", secondary_y=False, type='log')
fig.update_yaxes(title_text="Volatility", secondary_y=True)

fig.show()

In [ ]:
fig = px.area(df_sub, x=df_sub.index, y='rtn_005930')
fig.show()

In [ ]:
fig = px.scatter_3d(df_sub, x=df_sub.index, y='005930', z='AAPL')
fig.show()

Macro

In [ ]:
fdr.DataReader('FRED:ICSA', start='2020')

              ICSA
DATE
2020-01-04  217000
2020-01-11  203000
2020-01-18  211000
2020-01-25  200000
2020-02-01  191000
...            ...
2022-11-26  226000
2022-12-03  231000
2022-12-10  212000
2022-12-17  216000
2022-12-24  225000

[156 rows x 1 columns]

In [ ]:
df_macro = pd.DataFrame()
df_macro['UNRATE'] = fdr.DataReader('FRED:UNRATE', start='2000')
df_macro

            UNRATE
DATE
2000-01-01     4.0
2000-02-01     4.1
2000-03-01     4.0
2000-04-01     3.8
2000-05-01     4.0
...            ...
2022-07-01     3.5
2022-08-01     3.7
2022-09-01     3.5
2022-10-01     3.7
2022-11-01     3.7

[275 rows x 1 columns]

In [ ]:
fig = px.area(df_macro, y='UNRATE')
fig.show()

In [ ]:
df_macro

            UNRATE      CPI
DATE
2000-01-01     4.0  169.300
2000-02-01     4.1  170.000
2000-03-01     4.0  171.000
2000-04-01     3.8  170.900
2000-05-01     4.0  171.200
...            ...      ...
2022-07-01     3.5  295.271
2022-08-01     3.7  295.620
2022-09-01     3.5  296.761
2022-10-01     3.7  298.062
2022-11-01     3.7  298.349

[275 rows x 2 columns]

In [ ]:
df_macro['CPI'] = fdr.DataReader('FRED:CPIAUCSL', start='2000')
fig = px.area(df_macro, y='CPI')
fig.show()

In [ ]:
df_macro['CPI_yoy'] = (df_macro['CPI'] / df_macro['CPI'].shift(12) - 1) * 100
fig = px.bar(df_macro, y='CPI_yoy')
fig.show()

In [ ]:
df_multi = pd.concat([df_sub['AAPL'],df_macro['CPI_yoy']], axis=1)
df_multi

                  AAPL  CPI_yoy
2000-01-01         NaN      NaN
2000-02-01         NaN      NaN
2000-03-01         NaN      NaN
2000-04-01         NaN      NaN
2000-05-01         NaN      NaN
...                ...      ...
2022-12-29  129.610001      NaN
2022-12-30  129.929993      NaN
2023-01-02  129.929993      NaN
2023-01-03  125.070000      NaN
2023-01-04  125.070000      NaN

[3546 rows x 2 columns]

In [ ]:
df_multi.fillna(method='ffill', inplace=True)
df_multi.dropna(inplace=True)
df_multi

                  AAPL   CPI_yoy
2010-01-04    7.643214  2.621111
2010-01-05    7.656429  2.621111
2010-01-06    7.534643  2.621111
2010-01-07    7.520714  2.621111
2010-01-08    7.570714  2.621111
...                ...       ...
2022-12-29  129.610001  7.117879
2022-12-30  129.929993  7.117879
2023-01-02  129.929993  7.117879
2023-01-03  125.070000  7.117879
2023-01-04  125.070000  7.117879

[3425 rows x 2 columns]

In [ ]:
fig = px.line(df_multi, y=['AAPL', 'CPI_yoy'])
fig.show()

In [ ]:
fig = make_subplots(specs=[[{"secondary_y": True}]])

fig.add_trace(
    go.Scatter(x=df_multi.index, y=df_multi['AAPL'], name='AAPL'),
    secondary_y=False,
)

fig.add_trace(
    go.Scatter(x=df_multi.index, y=df_multi['CPI_yoy'], name='CPI'),
    secondary_y=True,
)

fig.update_yaxes(title_text="Price", secondary_y=False, type='log')
fig.update_yaxes(title_text="CPI", secondary_y=True)

fig.show()

In [ ]:
stocks = ['AAPL','MSFT','GOOGL','TSLA','META','F','KO']
df = pd.DataFrame()
for s in stocks:
    df_tmp = fdr.DataReader(s)
    df_tmp.rename(columns={'Close':s}, inplace=True)
    df = pd.concat([df,df_tmp[s]], axis=1)
df.fillna(method='ffill', inplace=True)
df.dropna(inplace=True)
dfr = df.iloc[-252:] / df.iloc[-252] * 100
dfr

In [ ]:
fig = go.Figure(data=[go.Surface(x=dfr.columns, y=dfr.index, z=dfr.values)])
fig.show()

[주말 감추기](https://plotly.com/python/time-series/#hiding-weekends-and-holidays)

In [ ]:
fig = px.area(df, x=df.index, y='AAPL')
fig.update_xaxes(
    rangebreaks=[
        dict(bounds=["sat", "mon"]), #hide weekends
        dict(values=["2022-12-25", "2021-01-01"])  # hide Christmas and New Year's
    ]
)
fig.show()